### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by adriendomoison** [devopsfaith/krakend#101]
Hi,

I created a karkend.json file with the designer and used docker install method + docker-compose as in the example to run the API's gateway.

When I am testing using Postman, I get an error 500 with the body being "Unexpected 'B'".

There is no error in the console and I could not find any resources on the web, what could I do to debug this issue and have more information about what's going on?

Thank you 👍

**Comment by kpacha** [comment]
Hi, @adriendomoison  and welcome to the KrakenD community.

No, there is not a more verbose mode than enabling the `DEBUG` level in your installation. But I think this should help you finding the root problem: http://www.krakend.io/docs/faq/#solution-to-invalid-responses

On the other hand, if you add here your config.json (without confidential data) and samples of the typical responses your backends are returning to the gateway, we'll check it too.

cheers!

**Comment by adriendomoison** [comment]
HI,

I believe it's an error in between something in KrakenD and Docker Networks but I can't figure out what I am doing wrong as it works without using the gateways, here are the files (thank you so much for giving it a look, that's much appreciated! 👍 )

```
{
  "version": 2,
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level": "ERROR",
      "prefix": "[KRAKEND]",
      "syslog": false,
      "stdout": true
    },
    "krakendesigner": {
      "endpoint_defaults": {
        "github.com/devopsfaith/krakend-ratelimit/juju/router": {
          "maxRate": 0,
          "clientMaxRate": 0
        }
      }
    }
  },
  "max_idle_connections": 250,
  "timeout": "3000ms",
  "read_timeout": "0s",
  "write_timeout": "0s",
  "idle_timeout": "0s",
  "read_header_timeout": "0s",
  "cache_ttl": "300s",
  "name": "ApiGoBoot Gateway",
  "sd_providers": {
    "hosts": [
      {
        "sd": "static",
        "host": "http://api.user.apigoboot:4200"
      },
      {
        "sd": "static",
        "host": "http://api.profile.apigoboot:4200"
      }
    ]
  },
  "endpoints": [
    {
      "endpoint": "/api/v1/users",
      "method": "POST",
      "concurrent_calls": 1,
      "extra_config": {
        "github_com/devopsfaith/krakend-httpsecure": {
          "disable": true,
          "allowed_hosts": [],
          "ssl_proxy_headers": {}
        },
        "github.com/devopsfaith/krakend-ratelimit/juju/router": {
          "maxRate": 0,
          "clientMaxRate": 0
        }
      },
      "querystring_params": [
        "create_profile"
      ],
      "backend": [
        {
          "url_pattern": "/api/v1/users",
          "extra_config": {
            "github.com/devopsfaith/krakend-oauth2-clientcredentials": {
              "is_disabled": true,
              "endpoint_params": {}
            }
          },
          "encoding": "json",
          "host": [
            "http://api.user.apigoboot:4200"
          ],
          "disable_host_sanitize": true
        }
      ]
    }
  ]
}
```

```
version: '3'
services:
  db:
    build: api-db
    container_name: apigoboot_db
    volumes:
      - ./api-db/pgdata:/pgdata
    ports:
      - "5432:5432"

  api_gateway:
    build:
      context: ./api-gateway
    container_name: apigoboot_api_gateway
    volumes:
      - ./api-gateway:/etc/krakend
    ports:
      - "4200:4200"

  api_user:
    build:
      context: ./user-micro-service
    container_name: apigoboot_api_user
    depends_on:
      - "db"
    volumes:
      - ./user-micro-service:/go/src/github.com/adriendomoison/apigoboot/user-micro-service/
    ports:
      - "4201:4200"
    links:
      - db
    networks:
      default:
        aliases:
          - api.user.apigoboot

  api_profile:
    build:
      context: ./profile-micro-service
    container_name: apigoboot_api_profile
    depends_on:
      - "db"
    volumes:
      - ./profile-micro-service:/go/src/github.com/adriendomoison/apigoboot/profile-micro-service/
    ports:
      - "4202:4200"
    links:
      - db
    networks:
      default:
        aliases:
          - api.profile.apigoboot

networks:
  default:
    external:
      name: apigoboot_network
```

Console : 
```
api_gateway_1  | [GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
api_gateway_1  | 
api_gateway_1  | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
api_gateway_1  |  - using env:  export GIN_MODE=release
api_gateway_1  |  - using code: gin.SetMode(gin.ReleaseMode)
api_gateway_1  | 
api_gateway_1  | [GIN-debug] GET    /__debug/*param           --> github.com/devopsfaith/krakend/router/gin.DebugHandler.func1 (5 handlers)
api_gateway_1  | [GIN-debug] POST   /__debug/*param           --> github.com/devopsfaith/krakend/router/gin.DebugHandler.func1 (5 handlers)
api_gateway_1  | [GIN-debug] PUT    /__debug/*param           --> github.com/devopsfaith/krakend/router/gin.DebugHandler.func1 (5 handlers)
api_gateway_1  | [GIN-debug] POST   /api/v1/users             --> github.com/gin-gonic/contrib/cache.CachePage.func1 (5 handlers)

api_gateway_1  | [GIN] 2018/03/14 - 23:03:43 | 500 |      69.465µs |      172.20.0.1 | GET      /api/v1/users?create_profile=true
```
