### ISSUE TITLE
Bug in parsing yaml format configuration files

### ISSUE THREAD

**Issue by x1ah** [devopsfaith/krakend#469]
**Describe the bug**
If use the yaml format configuration file, the nested map will not be parsed normally.

**To Reproduce**

```yaml
# config.yml

version: 2
timeout: 3000ms
cache_ttl: 300s
port: 8989
output_encoding: json
name: CoolUserService
endpoints:
  - endpoint: /_health
    extra_config:
      'github.com/devopsfaith/krakend/proxy':
        static:
          data:
            status: OK
          strategy: always
    backend:
      - url_pattern: /
        host:
          - 'http://fake-backend'
```

then run gateway with `./krakend-ce run -d -c config.yml`. After start, if run `curl localhost:8989/_health`, the static response will not be returned normally. Because the configuration file is parsed incorrectly. I found that the problem is in the viper package. 

```go
// main.go
package main

import (
	"fmt"

	viper "github.com/devopsfaith/krakend-viper"
)

func main() {
	parser := viper.New()
	cfg, _ := parser.Parse("config.yml")
	fmt.Printf("%+v\n", cfg.Endpoints[0].ExtraConfig["github.com/devopsfaith/krakend/proxy"].(map[string]interface{})["static"].(map[string]interface{})["data"])
}
```

This code snippet will panic, because `cfg.Endpoints[0].ExtraConfig["github.com/devopsfaith/krakend/proxy"].(map[string]interface{})["static"]` type is `map[interface{}]interface{}`, can't convert to `map[string]interface{}`. In krakend, appear here: https://github.com/devopsfaith/krakend/blob/5e10125d6f474676256f80a99d00010fb97a9b04/proxy/static.go#L71-L74

## Releated issue 
- https://github.com/go-yaml/yaml/issues/139
